tap "neurosnap/tap"
brew "asciinema"
brew "curl"
brew "direnv", args: ["HEAD"]
brew "eza", args: ["HEAD"]
brew "fish"
brew "fisher"
brew "git-interactive-rebase-tool"
brew "git-spice"
brew "hysteria", restart_service: :changed
brew "ntfy"
brew "prek"
brew "rustnet"
brew "starship"
brew "uv"
brew "vivid"
brew "xxhash"
brew "neurosnap/tap/zmx"
