tap "mdsakalu/tap"
brew "bat", args: ["HEAD"]
brew "zstd"
brew "curl"
brew "fish"
brew "fisher"
brew "git"
brew "git-interactive-rebase-tool"
brew "rustnet"
brew "tofrodos"
brew "ttl"
brew "xray"
cask "1password"
cask "aldente"
cask "alt-tab"
cask "android-platform-tools"
cask "apparency"
cask "discord"
cask "font-monaspace"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "helium-browser"
cask "iina"
cask "istat-menus"
cask "keyty"
cask "linearmouse"
cask "loop"
cask "openmtp"
cask "protonvpn"
cask "raycast"
cask "shottr"
cask "spotify"
cask "transmission"
cask "whatsapp"
cask "yubico-authenticator"
cask "zed"
cask "mdsakalu/tap/zsm", trusted: true
mas "Command X", id: 6448461551
mas "Shareful", id: 1522267256
mas "WireGuard", id: 1451685025
