brew "fish"
brew "fisher"
brew "git"
brew "tofrodos"
cask "1password"
cask "aldente"
cask "alt-tab"
cask "android-platform-tools"
cask "apparency"
cask "discord"
cask "font-monaspace"
cask "font-symbols-only-nerd-font"
cask "ghostty"
cask "helium-browser"
cask "iina"
cask "istat-menus"
cask "keyty"
cask "linearmouse"
cask "loop"
cask "openmtp"
cask "pdfcraft"
cask "protonvpn"
cask "raycast"
cask "shottr"
cask "spotify"
cask "transmission"
cask "whatsapp"
cask "yubico-authenticator"
cask "zed"
mas "Command X", id: 6448461551
mas "Shareful", id: 1522267256
mas "WireGuard", id: 1451685025
