"$schema" = "https://starship.rs/config-schema.json"

# Insert $fill and trailing space before $line_break
# Move less important modules to the right prompt
format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill \
$all\
$line_break\
$jobs\
$shlvl\
$character\
"""
palette = "catppuccin_mocha"

[battery]
disabled = true

[character]
format = "$symbol" # Remove trailing space

[cmd_duration]
format = "took [ $duration]($style) " # Add hourglass symbol (https://github.com/starship/starship/issues/6826)

[fill]
symbol = "·"
style = "237"

[jobs]
format = "[$symbol]($style)" # Remove number and trailing space

[shlvl]
format = "[$symbol]($style)" # Remove number and trailing space
symbol = "❯"
repeat = true
repeat_offset = 1
disabled = false


# Starship presets
# https://github.com/starship/starship/blob/ff0acb193eaa04ab63a8e56e1bd18019444b886f/docs/public/presets/toml/nerd-font-symbols.toml
# https://github.com/starship/starship/blob/ff0acb193eaa04ab63a8e56e1bd18019444b886f/docs/public/presets/toml/no-empty-icons.toml

[aws]
symbol = " "

[buf]
format = "(with [$symbol($version )]($style))"
symbol = " "

[bun]
format = "(via [$symbol($version )]($style))"
symbol = " "

[c]
format = "(via [$symbol($version(-$name) )]($style))"
symbol = " "

[cpp]
format = "(via [$symbol($version(-$name) )]($style))"
symbol = " "
disabled = false

[cmake]
format = "(via [$symbol($version )]($style))"
symbol = " "

[cobol]
format = "(via [$symbol($version )]($style))"

[conda]
symbol = " "

[crystal]
format = "(via [$symbol($version )]($style))"
symbol = " "

[daml]
format = "(via [$symbol($version )]($style))"

[dart]
format = "(via [$symbol($version )]($style))"
symbol = " "

[deno]
format = "(via [$symbol($version )]($style))"
symbol = " "

[directory]
truncation_length = 0   # Don't truncate parent directories
style = "bold lavender" # Catppuccin lavender
read_only = " "

[docker_context]
symbol = " "

[dotnet]
format = "(via [$symbol($version )(🎯 $tfm )]($style))"

[elixir]
format = '(via [$symbol($version \(OTP $otp_version\) )]($style))'
symbol = " "

[elm]
format = "(via [$symbol($version )]($style))"
symbol = " "

[erlang]
format = "(via [$symbol($version )]($style))"

[fennel]
format = "(via [$symbol($version )]($style))"
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "
style = "bold mauve" # Catppuccin mauve

[git_commit]
tag_disabled = false # Enable tag info
tag_symbol = "  "

[gleam]
format = "(via [$symbol($version )]($style))"

[golang]
format = "(via [$symbol($version )]($style))"
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
format = "(via [$symbol($version )]($style))"
symbol = " "

[haxe]
symbol = " "

[helm]
format = "(via [$symbol($version )]($style))"

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
format = "(via [$symbol($version )]($style))"
symbol = " "

[julia]
format = "(via [$symbol($version )]($style))"
symbol = " "

[kotlin]
format = "(via [$symbol($version )]($style))"
symbol = " "

[lua]
format = "(via [$symbol($version )]($style))"
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
format = "(via [$symbol($version )]($style))"
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
format = "(via [$symbol($version )]($style))"
symbol = " "

[ocaml]
format = '(via [$symbol($version )(\($switch_indicator$switch_name\) )]($style))'
symbol = " "

[opa]
format = "(via [$symbol($version )]($style))"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
format = "(is [$symbol$version]($style) )"
symbol = "󰏗 "

[perl]
format = "(via [$symbol($version )]($style))"
symbol = " "

[php]
format = "(via [$symbol($version )]($style))"
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[purescript]
format = "(via [$symbol($version )]($style))"

[python]
format = '(via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'
symbol = " "

[quarto]
format = "(via [$symbol($version )]($style))"

[raku]
format = "(via [$symbol($version-$vm_version )]($style))"

[red]
format = "(via [$symbol($version )]($style))"

[rlang]
format = "(via [$symbol($version )]($style))"
symbol = "󰟔 "

[ruby]
format = "(via [$symbol($version )]($style))"
symbol = " "

[rust]
format = "(via [$symbol($version )]($style))"
symbol = "󱘗 "

[scala]
format = "(via [$symbol($version )]($style))"
symbol = " "

[swift]
format = "(via [$symbol($version )]($style))"
symbol = " "

[typst]
format = "(via [$symbol($version )]($style))"

[vagrant]
format = "(via [$symbol($version )]($style))"

[vlang]
format = "(via [$symbol($version )]($style))"

[xmake]
format = "(via [$symbol($version )]($style))"
symbol = " "

[zig]
format = "(via [$symbol($version )]($style))"
symbol = " "


# Catppuccin palettes
# https://github.com/catppuccin/starship/tree/0cf91419f9649e9a47bb5c85797e4b83ecefe45c/themes

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
