#! /usr/bin/env bash

set -euo pipefail

git ls-files -z --others --ignored --directory --exclude-standard "${GIT_PREFIX:-.}" |
    xargs --null --no-run-if-empty eza --classify --icons --hyperlink --treat-dirs-as-files
