fish_add_path -ag /usr/local/opt/curl/bin
fish_add_path -ag /usr/local/opt/file-formula/bin
fish_add_path -ag /usr/local/opt/findutils/libexec/gnubin
fish_add_path -ag /usr/local/opt/gawk/libexec/gnubin
fish_add_path -ag /usr/local/opt/gnu-sed/libexec/gnubin
fish_add_path -ag /usr/local/opt/gnu-tar/libexec/gnubin
fish_add_path -ag /usr/local/opt/gnu-units/libexec/gnubin
fish_add_path -ag /usr/local/opt/gnu-which/libexec/gnubin
fish_add_path -ag /usr/local/opt/grep/libexec/gnubin
fish_add_path -ag /usr/local/opt/make/libexec/gnubin
fish_add_path -ag /usr/local/opt/uutils-coreutils/libexec/uubin
